title: Write for technology
author: Chetan Bhatia
email: 127chetan@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  All writing for technology serves a function. I write about creating functional content.

# social links
twitter_username: cgbhatia # DO NOT include the @ character, or else the build will fail!
github_username:  127chetan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
